site_name: ToolAgents Documentation
site_description: Documentation for the ToolAgents framework
site_author: Maximilian Winter

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

repo_name: Maximilian-Winter/ToolAgents
repo_url: https://github.com/Maximilian-Winter/ToolAgents

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Guides:
    - Basic Usage: guides/basic-usage.md
    - Custom Tools: guides/custom-tools.md
    - Chat History: guides/chat-history.md
    - Streaming: guides/streaming.md
  - Components:
    - Agents: components/agents.md
    - Tools: components/tools.md
    - Providers: components/providers.md
    - Messages: components/messages.md
  - API Reference:
    - Agents: api/agents.md
    - Tools: api/tools.md
    - Providers: api/providers.md
    - Messages: api/messages.md
    - Knowledge: api/knowledge.md
    - Utilities: api/utilities.md
  - Examples:
    - Basic Agents: examples/basic-agents.md
    - Advanced Agents: examples/advanced-agents.md
    - Web Research: examples/web-research.md
    - Code Interpreter: examples/code-interpreter.md
    - Memory: examples/memory.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/Maximilian-Winter"  target="_blank" rel="noopener">Maximilian Winter</a>

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Maximilian-Winter
    - icon: fontawesome/brands/twitter
      link: https://x.com/LumpenLue12
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/maximilian-winter-663737229/

plugins:
  - search